INSERT INTO `idiomas`(`idIdioma`, `idioma`)VALUES 
('','English'),
('','German'),
('','French'),
('','Japanese'),
('','Danish'),
('','Spanish'),
('','Italian'),
('','Dutch'),
('','Norwegian'),
('','Portuguese'),
('','Finnish'),
('','Swedish'),
('','Czech'),
('','Hungarian'),
('','Polish'),
('','Romanian'),
('','Croatian'),
('','Slovak'),
('','Slovene'),
('','Greek'),
('','Bulgarian'),
('','Russian'),
('','Turkish'),
('','British English'),
('','Estonian'),
('','Latvian'),
('','Lithuanian'),
('','Portuguese Brazil'),
('','Traditional Chinese'),
('','Korean'),
('','Simplified Chinese'),
('','Arabic'),
('','Thai')