CREATE TABLE `gameparadise`.`plataformas` ( `idPlataforma` INT NOT NULL AUTO_INCREMENT , `Plataforma` VARCHAR(60) NOT NULL , PRIMARY KEY (`idPlataforma`)) ENGINE = InnoDB;
INSERT INTO `plataformas`(`idPlataforma`, `Plataforma`) VALUES 
('','PC'),
('','XBOX'),
('','XBOX 360'),
('','XBOX One'),
('','XBOX Series X|S'),
('','PSP'),
('','PSP Vita'),
('','PlayStation'),
('','PlayStation 2'),
('','PlayStation 3'),
('','PlayStation 4'),
('','PlayStation 5'),
('','Switch'),
('','Gamecube'),
('','3DS'),
('','2DS'),
('','DS'),
('','Wii'),
('','Wii U'),
('','Nintendo 64'),
('','SNES'),
('','NES'),
('','GameBoy'),
('','GameBoy Color'),
('','GameBoy Advance'),
('','Android'),
('','IOS')